//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliverySchedule
    {
        public int ID { get; set; }
        public int Order_ID { get; set; }
        public int DeliveryMan_ID { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string Address { get; set; }
        public string Status { get; set; }
    }
}
