//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpadesGroceryEntities : DbContext
    {
        public SpadesGroceryEntities()
            : base("name=SpadesGroceryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DeliverySchedule> DeliverySchedules { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Ordered_Products> Ordered_Products { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ReturnRefund> ReturnRefunds { get; set; }
        public virtual DbSet<ReviewRating> ReviewRatings { get; set; }
        public virtual DbSet<Token> Tokens { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<VendorProduct> VendorProducts { get; set; }
    }
}
